version: "3.9"
name: bytebot

services:
  postgres:
    image: postgres:16-alpine
    container_name: bytebot-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bytebotdb
    networks:
      - bytebot-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bytebot-desktop:
    build:
      context: ./packages
      dockerfile: bytebotd/Dockerfile
    container_name: bytebot-desktop
    restart: unless-stopped
    shm_size: "2g"
    hostname: computer
    privileged: true
    ports:
      - "9990:9990"   # noVNC + bytebotd service
    environment:
      DISPLAY: ":0"
    networks:
      - bytebot-network
    depends_on:
      - postgres

  bytebot-agent:
    build:
      context: ./packages
      dockerfile: bytebot-agent/Dockerfile
    container_name: bytebo_
